In [4]:
import pandas as pd

In [5]:
# Read in the dataset
df = pd.read_sas("../data/llcp2017.xpt", encoding='utf-8')

/Users/adamysyim/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sas/sas_xport.py:475: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[x] = v

In [54]:
# check number of rows and columns
df.shape

(450016, 358)

In [55]:
# check that the first 5 rows with full display of columns
pd.set_option('display.max_columns', 300)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELLFON4,LADULT,NUMADULT,NUMMEN,NUMWOMEN,SAFETIME,CTELNUM1,CELLFON5,CADULT,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,CHOLCHK1,TOLDHI2,CHOLMED1,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAI1,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1A,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ECIGARET,ECIGNOW,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUIT2,FRUITJU2,FVGREEN1,FRENCHF1,POTATOE1,VEGETAB2,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,SEATBELT,FLUSHOT6,FLSHTMY2,PNEUVAC3,SHINGLE2,HIVTST6,HIVTSTD3,HIVRISK5,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,COPDCOGH,COPDFLEM,COPDBRTH,COPDBTST,COPDSMOK,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,BPEATHBT,BPSALT,BPALCHOL,BPEXER,BPEATADV,BPSLTADV,BPALCADV,BPEXRADV,BPMEDADV,BPHI2MR,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,ASTHMAGE,ASATTACK,...,TETANUS,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSCN,CAREGIV1,CRGVREL2,CRGVLNG1,CRGVHRS1,CRGVPRB2,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,EMTSUPRT,LSATISFY,SDHBILLS,SDHMOVE,HOWSAFE1,SDHFOOD,SDHMEALS,SDHMONEY,SDHSTRES,SXORIENT,TRNSGNDR,FIREARM4,GUNLOAD,LOADULK2,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,QSTVER,QSTLANG,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HCVU651,_RFHYPE5,_CHOLCH1,_RFCHOL1,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_LMTACT1,_LMTWRK1,_LMTSCL1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,_ECIGSTS,_CURECIG,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA2_,FRUTDA2_,GRENDA1_,FRNCHDA_,POTADA1_,VEGEDA2_,_MISFRT1,_MISVEG1,_FRTRES1,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1.0,1.0,01302017,01,30,2017,1100.0,2017000001,2.017000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,88.0,88.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,1.0,68.0,2.0,2.0,3.0,2.0,2.0,3.0,6.0,1.0,2.0,NaN,1.0,1.0,7.0,88.0,6.0,1.0,162.0,505.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,NaN,888.0,NaN,NaN,NaN,102.0,555.0,203.0,201.0,201.0,101.0,1.0,6.0,103.0,30.0,54.0,103.0,30.0,103.0,1.0,1.0,102016.0,1.0,1.0,1.0,92016.0,2.0,NaN,NaN,2.0,102.0,101.0,88.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,11011.0,26.296801,1.0,26.296801,1.0,NaN,NaN,NaN,NaN,1.0,0.597042,185.477444,79.425947,1.0,1.0,1.0,9.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,74.0,6.0,65.0,165.0,7348.0,2696.0,3.0,2.0,1.0,4.0,4.0,4.0,1.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,200.0,43.0,1.400000e+01,1.400000e+01,100.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,200.0,171.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,6.800000e+01,90.0,2062.0,353.0,2.000000e+00,2.0,30.0,30.0,3000.0,3000.0,9.000000e+01,90.0,3.000000e+03,5.397605e-79,1.800000e+02,180.0,360.0,9.000000e+01,9.000000e+01,1.800000e+02,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,1.0,01122017,01,12,2017,1100.0,2017000002,2.017000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,6.0,1.0,1.0,2.0,1.0,2.0,7.0,88.0,8.0,1.0,211.0,511.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,NaN,888.0,NaN,NaN,NaN,103.0,555.0,101.0,555.0,555.0,101.0,1.0,34.0,102.0,100.0,64.0,230.0,100.0,102.0,1.0,1.0,12017.0,1.0,2.0,1.0,52013.0,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11011.0,26.296801,1.0,26.296801,1.0,NaN,NaN,NaN,NaN,1.0,0.597042,185.477444,89.694580,1.0,1.0,1.0,9.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,10.0,2.0,67.0,6.0,71.0,180.0,9571.0,2943.0,3.0,2.0,1.0,4.0,5.0,4.0,1.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,300.0,100.0,5.397605e-79,5.397605e-79,100.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,300.0,200.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,5.397605e-79,35.0,2315.0,397.0,5.397605e-79,1.0,60.0,60.0,2000.0,7000.0,5.397605e-79,420.0,2.000000e+03,5.397605e-79,5.397605e-79,420.0,420.0,5.397605e-79,5.397605e-79,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,1.0,1.0,01102017,01,10,2017,1100.0,2017000003,2.017000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,3.0,NaN,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,2.0,195.0,602.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,NaN,101.0,1.0,88.0,1.0,202.0,302.0,201.0,202.0,555.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,122016.0,1.0,2.0,2.0,NaN,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,3.0,11011.0,26.296801,2.0,52.593603,1.0,NaN,NaN,NaN,NaN,1.0,0.597042,370.954888,440.121376,1.0,1.0,1.0,9.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,70.0,6.0,74.0,188.0,8845.0,2504.0,3.0,2.0,1.0,1.0,9.0,4.0,1.0,4.0,1.0,1.0,1.400000e+01,1.0,1.000000e+02,1.0,7.000000e+00,29.0,14.0,2.900000e+01,5.397605e-79,14.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,36.0,57.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2150.0,369.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,2.0
3,1.0,1.0,02082017,02,08,2017,1200.0,2017000004,2.017000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0,1.0,2.0,1.0,73.0,NaN,NaN,NaN,NaN,2.0,3.0,3.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,1.0,2.0,170.0,507.0,NaN,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,NaN,888.0,NaN,NaN,NaN,301.0,555.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,888.0,402.0,3.0,2.0,2.0,3.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,11011.0,26.296801,1.0,26.296801,1.0,NaN,NaN,NaN,NaN,1.0,0.597042,185.477444,194.867164,2.0,1.0,1.0,9.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,2.0,3.0,3.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,73.0,6.0,67.0,170.0,7711.0,2663.0,3.0,2.0,1.0,1.0,1.0,4.0,1.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,3.0,NaN,NaN,NaN,NaN,5.397605e-79,3.000000e+00,1.0,5.397605e-79,3.0,NaN,2.0,9.0,1.0,1.0,5.397605e-79,1.000000e+00,9.0,NaN,NaN,2099.0,360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
4,1.0,1.0,01302017,01,30,2017,1100.0,2017000005,2.017000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,14.0,88.0,14.0,1.0,1.0,2.0,1.0,3.0,NaN,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,2.0,2.0,NaN,2.0,2.0,8.0,88.0,2.0,2.0,140.0,505.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,3.0,2.0,NaN,888.0,NaN,NaN,NaN,101.0,202.0,201.0,303.0,201.0,303.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,11011.0,26.296801,1.0,26.296801,1.0,NaN,NaN,NaN,NaN,9.0,NaN,252.493865,169.087888,2.0,3.0,1.0,9.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,10.0,2.0,69.0,6.0,65.0,165.0,6350.0,2330.0,2.0,1.0,1.0,1.0,1.0,3.0,1.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.900000e+01,100.0,14.0,1.000000e+01,1.400000e+01,10.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00,129.0,48.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2247.0,385.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,2.0,2.0,2.0,2.0

In [56]:
# select columns for analysis
df_sel = df[['DIABETE3','_PHYS14D','PA1VIGM_','_PACAT1','_PA150R2','_PA300R2','_PA30021','_PAINDX1','_PASTRNG',
                    '_PAREC1','_VEGLT1A','_FRTLT1A','POTADA1_','FRNCHDA_','GRENDA1_','FRUTDA2_','FTJUDA2_','_RFDRHV5',
                    '_RFBING5','_CURECIG','_ECIGSTS','_RFSMOK3','_SMOKER3','_INCOMG','_EDUCAG','_BMI5','_BMI5CAT','_RFBMI5',
                    '_MICHD','CVDSTRK3','_RFCHOL1','TOLDHI2','_RFHYPE5','_MENT14D','MENTHLTH','SEX','_AGEG5YR','_AGE_G','_AGE65YR']]

In [57]:
df_sel.head()

,DIABETE3,_PHYS14D,PA1VIGM_,_PACAT1,_PA150R2,_PA300R2,_PA30021,_PAINDX1,_PASTRNG,_PAREC1,_VEGLT1A,_FRTLT1A,POTADA1_,FRNCHDA_,GRENDA1_,FRUTDA2_,FTJUDA2_,_RFDRHV5,_RFBING5,_CURECIG,_ECIGSTS,_RFSMOK3,_SMOKER3,_INCOMG,_EDUCAG,_BMI5,_BMI5CAT,_RFBMI5,_MICHD,CVDSTRK3,_RFCHOL1,TOLDHI2,_RFHYPE5,_MENT14D,MENTHLTH,SEX,_AGEG5YR,_AGE_G,_AGE65YR
0,1.0,1.0,1.800000e+02,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.400000e+01,1.400000e+01,43.0,200.0,5.397605e-79,1.0,1.0,1.0,4.0,1.0,4.0,4.0,4.0,2696.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,88.0,2.0,11.0,6.0,2.0
1,3.0,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,100.0,300.0,5.397605e-79,1.0,1.0,1.0,4.0,1.0,4.0,5.0,4.0,2943.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,88.0,1.0,10.0,6.0,2.0
2,3.0,1.0,NaN,4.0,3.0,3.0,2.0,2.0,2.0,4.0,2.0,2.0,5.397605e-79,2.900000e+01,14.0,29.0,7.000000e+00,1.0,1.0,1.0,4.0,1.0,4.0,9.0,1.0,2504.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,88.0,1.0,11.0,6.0,2.0
3,1.0,1.0,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,2.0,NaN,NaN,NaN,3.0,5.397605e-79,1.0,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2663.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,88.0,2.0,11.0,6.0,2.0
4,3.0,3.0,NaN,4.0,3.0,3.0,2.0,2.0,2.0,4.0,2.0,1.0,1.400000e+01,1.000000e+01,14.0,100.0,2.900000e+01,1.0,1.0,1.0,4.0,1.0,3.0,1.0,1.0,2330.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,88.0,2.0,10.0,6.0,2.0

In [58]:
# drop missing values
df_sel = df_sel.dropna()
df_sel['DIABETE3'].value_counts()

3.0    206081
1.0     28348
4.0      4242
2.0      1619
7.0       151
9.0        19
Name: DIABETE3, dtype: int64

In [59]:
## DIABETE3 - check,replace,remove
 # 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
 # remove 7(don't know) and 9(refused)
df_sel['DIABETE3'] = df_sel['DIABETE3'].astype(int)
df_sel['DIABETE3'].replace({2:0,3:0,1:2,4:1},inplace=True)
df_sel['DIABETE3'].value_counts()

0    207700
2     28348
1      4242
7       151
9        19
Name: DIABETE3, dtype: int64

In [60]:
df_sel = df_sel[df_sel['DIABETE3'] != 7]
df_sel = df_sel[df_sel['DIABETE3'] != 9]
df_sel['DIABETE3'].value_counts()

0    207700
2     28348
1      4242
Name: DIABETE3, dtype: int64

In [61]:
## _PHYS14D - check,replace,remove
 # removing 9(don't know)
 # change order and scale 
  # 1 >> 0 (Zero days when physical health not good)
  # 2 >> 1 (1-13 days when physical health not good)
  # 3 >> 2(14+ days when physical health not good)
  # Inactive 4 >> 0 
df_sel=df_sel[df_sel['_PHYS14D'] != 9]
df_sel['_PHYS14D'].replace({1:0,2:1,3:2},inplace=True)
df_sel['_PHYS14D'] = df_sel['_PHYS14D'].astype(int)
df_sel['_PHYS14D'].value_counts()

0    156768
1     57244
2     23438
Name: _PHYS14D, dtype: int64

In [62]:
## PA1VIGM_ - check,replace,remove
df_sel['PA1VIGM_'] = df_sel['PA1VIGM_'].round(0)
df_sel['PA1VIGM_'].value_counts()

0.0       124268
120.0       6934
180.0       6586
60.0        6466
90.0        5184
           ...
3164.0         1
3040.0         1
2464.0         1
908.0          1
2920.0         1
Name: PA1VIGM_, Length: 1526, dtype: int64

In [63]:
## _PACAT1 - check,replace,remove
 # removing 9(don't know)
 # change order and scale (inactive(0) to highly active(3)) 
  # Highly Active 1 >> 4
  # Active 2 >> 3
  # Insufficiently Active 3 >> 1
  # Inactive 4 >> 0 
df_sel=df_sel[df_sel['_PACAT1'] != 9]
df_sel['_PACAT1'] = df_sel['_PACAT1'].astype(int)
df_sel['_PACAT1'].replace({1:3,2:2,3:1,4:0},inplace=True)
df_sel['_PACAT1'].value_counts()

3    109896
2     58054
1     57636
0      4263
Name: _PACAT1, dtype: int64

In [64]:
## _PA150R2 - check,replace,remove
# change order and scale 
 # 1 >> 2
 # 2 >> 1
 # 3 >> 0
df_sel['_PA150R2'].replace({1:2,2:1,3:0},inplace=True)
df_sel['_PA150R2'] = df_sel['_PA150R2'].astype(int)
df_sel['_PA150R2'].value_counts()

2    167950
1     57636
0      4263
Name: _PA150R2, dtype: int64

In [65]:
## _PA300R2 - check,replace,remove
 # change order and scale 
  # 1 >> 2
  # 2 >> 1
  # 3 >> 0
df_sel['_PA300R2'].replace({1:2,2:1,3:0},inplace=True)   
df_sel['_PA300R2'] = df_sel['_PA300R2'].astype(int)
df_sel['_PA300R2'].value_counts()

1    115690
2    109896
0      4263
Name: _PA300R2, dtype: int64

In [66]:
## _PA30021 - check,replace,remove
# change order and scale 
 # 1 >> 1 (301+minutes)
 # 2 >> 0 (0-300minutes)
df_sel['_PA30021'].replace({1:1,2:0},inplace=True)  
df_sel['_PA30021'] = df_sel['_PA30021'].astype(int)
df_sel['_PA30021'].value_counts()

0    119953
1    109896
Name: _PA30021, dtype: int64

In [67]:
## _PAINDX1 - check,replace,remove
 # change order and scale 
  # 1 >> 1 (Meet Aerobic Recommendations)
  # 2 >> 0 (Did Not Meet Aerobic Recommendations)
df_sel['_PAINDX1'].replace({1:1,2:0},inplace=True)  
df_sel['_PAINDX1'] = df_sel['_PAINDX1'].astype(int)
df_sel['_PAINDX1'].value_counts()

1    167950
0     61899
Name: _PAINDX1, dtype: int64

In [68]:
## _PASTRNG - check,replace,remove
 # removing 9(don't know)
 # change order and scale 
  # 1 >> 1 (Meet muscle strengthening recommendations)
  # 2 >> 0 (Did not meet muscle strengthening recommendations)
df_sel=df_sel[df_sel['_PASTRNG'] != 9]
df_sel['_PASTRNG'].replace({1:1,2:0},inplace=True)
df_sel['_PASTRNG'] = df_sel['_PASTRNG'].astype(int)
df_sel['_PASTRNG'].value_counts()

0    145529
1     82057
Name: _PASTRNG, dtype: int64

In [69]:
## _PAREC1 - check,replace,remove
 # change order, scale, merge 
  # 1 >> 2 (Met Both Guidelines)
  # 2 and 3 >> 1 (Met Aerobic Guidelines Only or Met Strengthening Guidelines Only)
  # 4 >> 0 (Did not meet Either Guideline)
df_sel['_PAREC1'].replace({1:2,2:1,3:1,4:0},inplace=True)
df_sel['_PAREC1'] = df_sel['_PAREC1'].astype(int)
df_sel['_PAREC1'].value_counts()

1    121678
2     63295
0     42613
Name: _PAREC1, dtype: int64

In [70]:
## _VEGLT1A - check,replace,remove
 # removing 9(don't know)
 # change order, scale
  # 1 >> 1 (Consumed vegetables one or more times per day)
  # 2 >> 0 (Consumed vegetables less than one time per day)
df_sel=df_sel[df_sel['_VEGLT1A'] != 9]
df_sel['_VEGLT1A'].replace({1:1,2:0},inplace=True)
df_sel['_VEGLT1A'] = df_sel['_VEGLT1A'].astype(int)
df_sel['_VEGLT1A'].value_counts()

1    197152
0     29553
Name: _VEGLT1A, dtype: int64

In [71]:
## _FRTLT1A - check,replace,remove
 # change order, scale
  # 1 >> 1 (Consumed fruit one or more times per day)
  # 2 >> 0 (Consumed fruit less than one time per day)
df_sel['_FRTLT1A'].replace({1:1,2:0},inplace=True)
df_sel['_FRTLT1A'] = df_sel['_FRTLT1A'].astype(int)
df_sel['_FRTLT1A'].value_counts()

1    158808
0     67897
Name: _FRTLT1A, dtype: int64

In [72]:
## POTADA1_ - check,replace,remove
df_sel['POTADA1_'] = df_sel['POTADA1_'].round(0)
df_sel['POTADA1_'].value_counts()

14.0      39416
29.0      30396
0.0       24993
7.0       21668
43.0      18329
          ...
1800.0        1
5300.0        1
7000.0        1
1400.0        1
293.0         1
Name: POTADA1_, Length: 84, dtype: int64

In [73]:
## FRNCHDA_ - check,replace,remove
df_sel['FRNCHDA_'] = df_sel['FRNCHDA_'].round(0)
df_sel['FRNCHDA_'].value_counts()

14.0      40671
0.0       39204
7.0       27363
3.0       23862
29.0      23265
          ...
7500.0        1
1400.0        1
293.0         1
303.0         1
240.0         1
Name: FRNCHDA_, Length: 83, dtype: int64

In [74]:
## GRENDA1_ - check,replace,remove
 # removing extreme value
df_sel = df_sel[df_sel['GRENDA1_'] >= 1]    
df_sel['GRENDA1_'].value_counts()

100.0     52190
43.0      29100
29.0      24155
57.0      18347
14.0      17194
          ...
123.0         1
329.0         1
140.0         1
1100.0        1
9100.0        1
Name: GRENDA1_, Length: 105, dtype: int64

In [75]:
## FRUTDA2_ - check,replace,remove
df_sel = df_sel[df_sel['FRUTDA2_'] >= 1] 
df_sel['FRUTDA2_'].value_counts()

100.0     68734
200.0     44131
300.0     17000
43.0      16567
29.0      10772
          ...
2900.0        1
160.0         1
173.0         1
757.0         1
183.0         1
Name: FRUTDA2_, Length: 120, dtype: int64

In [76]:
## FTJUDA2_ - check,replace,remove
df_sel['FTJUDA2_'] = df_sel['FTJUDA2_'].round(0)
df_sel['FTJUDA2_'].value_counts()

0.0       86533
100.0     32803
14.0      14226
29.0      12762
7.0       10190
          ...
1414.0        1
900.0         1
386.0         1
186.0         1
471.0         1
Name: FTJUDA2_, Length: 89, dtype: int64

In [77]:
## _RFDRHV5 - check,replace,remove
 # removing 9(don't know)
df_sel=df_sel[df_sel['_RFDRHV5'] != 9]
df_sel['_RFDRHV5'] = df_sel['_RFDRHV5'].astype(int)
df_sel['_RFDRHV5'].value_counts()

1    198373
2     12869
Name: _RFDRHV5, dtype: int64

In [78]:
## _RFBING5 - check,replace,remove
 # removing 9(don't know)
 # change order, scale
  # 1 >> 0 (No)
  # 2 >> 1 (Yes)
df_sel=df_sel[df_sel['_RFBING5'] != 9]
df_sel['_RFBING5'].replace({1:0,2:1},inplace=True)
df_sel['_RFBING5'] = df_sel['_RFBING5'].astype(int)
df_sel['_RFBING5'].value_counts()

0    181470
1     29106
Name: _RFBING5, dtype: int64

In [79]:
## _CURECIG - check,replace,remove
 # removing 9(don't know)
 # change order, scale
  # 1 >> 1 (Current E-cigarette user)
  # 2 >> 0 (Not currently using E-cigarettes)
df_sel=df_sel[df_sel['_CURECIG'] != 9]
df_sel['_CURECIG'].replace({1:1,2:0},inplace=True)
df_sel['_CURECIG'] = df_sel['_CURECIG'].astype(int)
df_sel['_CURECIG'].value_counts()

1    205028
0      5332
Name: _CURECIG, dtype: int64

In [80]:
## _ECIGSTS - check,replace,remove
 # change order, scale
  # 1 >> 3 (Current E-cigarette user - uses every day)
  # 2 >> 2 (Current E-cigarette user - uses some days)
  # 3 >> 1 (Former E-cigarette user)
  # 4 >> 0 (Never used E-cigarettes)
df_sel['_ECIGSTS'].replace({1:3,2:2,3:1,4:0},inplace=True)   
df_sel['_ECIGSTS'] = df_sel['_ECIGSTS'].astype(int)
df_sel['_ECIGSTS'].value_counts()

0    183075
1     21953
2      3408
3      1924
Name: _ECIGSTS, dtype: int64

In [81]:
##  _RFSMOK3 - check,replace,remove
 # removing 9(don't know)
 # change order, scale
  # 1 >> 0 (No)
  # 2 >> 1 (Yes)
df_sel=df_sel[df_sel['_RFSMOK3'] != 9]
df_sel['_RFSMOK3'].replace({1:0,2:1},inplace=True) 
df_sel['_RFSMOK3'] = df_sel['_RFSMOK3'].astype(int)
df_sel['_RFSMOK3'].value_counts()

0    186827
1     22793
Name: _RFSMOK3, dtype: int64

In [82]:
##  _SMOKER3 - check,replace,remove
 # change order, scale
  # 1 >> 3 (Current smoker - now smokes every day)
  # 2 >> 2 (Current smoker - now smokes some days)
  # 3 >> 1 (Former smoker)
  # 4 >> 0 (Never smoked)
df_sel['_SMOKER3'].replace({4:0,3:1,2:2,1:3},inplace=True)
df_sel['_SMOKER3'] = df_sel['_SMOKER3'].astype(int)
df_sel['_SMOKER3'].value_counts()

0    125510
1     61317
3     14857
2      7936
Name: _SMOKER3, dtype: int64

In [83]:
##  _INCOMG - check,replace,remove
 # removing 9(don't know)
 # change order, scale

df_sel=df_sel[df_sel['_INCOMG'] != 9]
df_sel['_INCOMG'] = df_sel['_INCOMG'].astype(int)
df_sel['_INCOMG'].value_counts()

5    111267
4     25680
2     22504
3     16860
1     11557
Name: _INCOMG, dtype: int64

In [84]:
##  _EDUCAG - check,replace,remove
 # removing 9(don't know)
df_sel=df_sel[df_sel['_EDUCAG'] != 9]
df_sel['_EDUCAG'] = df_sel['_EDUCAG'].astype(int)
df_sel['_EDUCAG'].value_counts()

4    91834
3    50641
2    38604
1     6681
Name: _EDUCAG, dtype: int64

In [85]:
##  _BMI5 - check,replace,remove
 # THe original value is BMI * 100. Therefore, divide every value with 100
df_sel['_BMI5'] = df_sel['_BMI5'].div(100).round(0)
df_sel['_BMI5'] = df_sel['_BMI5'].astype(int)
df_sel['_BMI5'].value_counts()

27    18850
26    15963
24    15581
25    13297
28    12440
      ...
82        1
86        1
69        1
72        1
84        1
Name: _BMI5, Length: 76, dtype: int64

In [86]:
## _RFBMI5 - check,replace,remove
# removing 9(don't know)
 # change order, scale
  # 1 >> 0 (No)
  # 2 >> 1 (Yes - obese)
df_sel=df_sel[df_sel['_RFBMI5'] != 9]
df_sel['_RFBMI5'].replace({1:0,2:1},inplace=True)
df_sel['_RFBMI5'] = df_sel['_RFBMI5'].astype(int)
df_sel['_RFBMI5'].value_counts()

1    125937
0     61823
Name: _RFBMI5, dtype: int64

In [87]:
## _BMI5CAT - check,replace,remove
df_sel['_BMI5CAT'] = df_sel['_BMI5CAT'].astype(int)
df_sel['_BMI5CAT'].value_counts()

3    71998
2    59616
4    53939
1     2207
Name: _BMI5CAT, dtype: int64

In [88]:
## _MICHD - check,replace,remove
 # change order, scale
  # 1 >> 1 (Reported having MI or CHD)
  # 2 >> 0 (Did not report having MI or CHD)
df_sel['_MICHD'].replace({1:1,2:0},inplace=True)
df_sel['_MICHD'] = df_sel['_MICHD'].astype(int)
df_sel['_MICHD'].value_counts()

0    173713
1     14047
Name: _MICHD, dtype: int64

In [89]:
## CVDSTRK3 - check,replace,remove
 # removing 7(don't know) 9(refused)
 # change order, scale
  # 1 >> 1 (Yes)
  # 2 >> 0 (No)

df_sel=df_sel[df_sel['CVDSTRK3'] != 7]
df_sel=df_sel[df_sel['CVDSTRK3'] != 9]
df_sel['CVDSTRK3'].replace({1:1,2:0},inplace=True)
df_sel['CVDSTRK3'] = df_sel['CVDSTRK3'].astype(int)
df_sel['CVDSTRK3'].value_counts()

0    181613
1      5893
Name: CVDSTRK3, dtype: int64

In [90]:
## _RFCHOL1 - check,replace,remove
 # change order, scale
  # 1 >> 0 (No)
  # 2 >> 1 (Yes)
df_sel['_RFCHOL1'].replace({1:0,2:1},inplace=True)  
df_sel['_RFCHOL1'] = df_sel['_RFCHOL1'].astype(int)
df_sel['_RFCHOL1'].value_counts()

0    117568
1     69938
Name: _RFCHOL1, dtype: int64

In [91]:
## TOLDHI2 - check,replace,remove
 # change order, scale
  # 1 >> 1 (Yes)
  # 2 >> 0 (No)
df_sel['TOLDHI2'].replace({1:1,2:0},inplace=True)  
df_sel['TOLDHI2'] = df_sel['TOLDHI2'].astype(int)
df_sel['TOLDHI2'].value_counts()

0    117568
1     69938
Name: TOLDHI2, dtype: int64

In [92]:
## _RFHYPE5 - check,replace,remove
 # removing 9(don't know)
 # change order, scale
  # 1 >> 0 (No)
  # 2 >> 1 (Yes)
df_sel=df_sel[df_sel['_RFHYPE5'] != 9]
df_sel['_RFHYPE5'].replace({1:0,2:1},inplace=True) 
df_sel['_RFHYPE5'] = df_sel['_RFHYPE5'].astype(int)
df_sel['_RFHYPE5'].value_counts()

0    115640
1     71702
Name: _RFHYPE5, dtype: int64

In [93]:
## _MENT14D - check,replace,remove
 # removing 9(don't know)
 # change order, scale
  # 1 >> 2 (Zero days when mental health not good)
  # 2 >> 1 (1-13 days when mental health not good)
  # 3 >> 0 (14+ days when mental health not good)
df_sel=df_sel[df_sel['_MENT14D'] != 9]
df_sel['_MENT14D'].replace({1:2,2:1,3:0},inplace=True) 
df_sel['_MENT14D'] = df_sel['_MENT14D'].astype(int)
df_sel['_MENT14D'].value_counts()

2    128895
1     42268
0     15128
Name: _MENT14D, dtype: int64

In [94]:
## MENTHLTH - check,replace,remove
 # change 88 to 0 (no bad mental health days)
df_sel['MENTHLTH'] = df_sel['MENTHLTH'].replace({88:0})    
df_sel['MENTHLTH'].value_counts()

0.0     128895
2.0      10423
1.0       7085
5.0       6936
30.0      6595
3.0       5931
10.0      4720
15.0      3871
4.0       2892
7.0       2523
20.0      2275
6.0        813
14.0       801
25.0       749
8.0        477
12.0       314
28.0       221
21.0       121
29.0       109
18.0        87
16.0        65
9.0         65
27.0        54
13.0        51
17.0        46
22.0        44
11.0        38
24.0        30
26.0        29
23.0        24
19.0         7
Name: MENTHLTH, dtype: int64

In [95]:
## SEX - check,replace,remove
df_sel['SEX'] = df_sel['SEX'].astype(int)
df_sel['SEX'].value_counts()

2    99907
1    86384
Name: SEX, dtype: int64

In [96]:
## _AGEG5YR - check,replace,remove
df_sel['_AGEG5YR'] = df_sel['_AGEG5YR'].astype(int)
df_sel['_AGEG5YR'].value_counts()

10    23256
9     23146
8     21025
11    17847
7     17474
6     14351
5     11866
4     11558
12    10977
13    10452
3      9885
2      7699
1      6755
Name: _AGEG5YR, dtype: int64

In [97]:
## _AGE_G - check,replace,remove
df_sel['_AGE_G'] = df_sel['_AGE_G'].astype(int)
df_sel['_AGE_G'].value_counts()

6    62532
5    44171
4    31825
3    23424
2    17584
1     6755
Name: _AGE_G, dtype: int64

In [98]:
## _AGE65YR - check,replace,remove
df_sel['_AGE65YR'] = df_sel['_AGE65YR'].astype(int)
df_sel['_AGE65YR'].value_counts()

1    123759
2     62532
Name: _AGE65YR, dtype: int64

In [99]:
df_sel['DIABETE3'].value_counts()

0    162051
2     21111
1      3129
Name: DIABETE3, dtype: int64

In [100]:
df_sel.head()

,DIABETE3,_PHYS14D,PA1VIGM_,_PACAT1,_PA150R2,_PA300R2,_PA30021,_PAINDX1,_PASTRNG,_PAREC1,_VEGLT1A,_FRTLT1A,POTADA1_,FRNCHDA_,GRENDA1_,FRUTDA2_,FTJUDA2_,_RFDRHV5,_RFBING5,_CURECIG,_ECIGSTS,_RFSMOK3,_SMOKER3,_INCOMG,_EDUCAG,_BMI5,_BMI5CAT,_RFBMI5,_MICHD,CVDSTRK3,_RFCHOL1,TOLDHI2,_RFHYPE5,_MENT14D,MENTHLTH,SEX,_AGEG5YR,_AGE_G,_AGE65YR
0,2,0,180.0,3,2,2,1,1,1,2,1,1,14.0,14.0,43.0,200.0,0.0,1,0,1,0,0,0,4,4,27,3,1,0,0,1,1,1,2,0.0,2,11,6,2
1,0,0,0.0,3,2,2,1,1,1,2,1,1,0.0,0.0,100.0,300.0,0.0,1,0,1,0,0,0,5,4,29,3,1,0,0,0,0,1,2,0.0,1,10,6,2
5,0,1,60.0,1,1,1,0,0,0,0,1,0,43.0,14.0,29.0,2.0,7.0,1,0,1,0,1,3,2,2,27,3,1,1,0,0,0,1,2,0.0,1,12,6,2
9,0,1,0.0,3,2,2,1,1,0,1,1,1,20.0,300.0,100.0,700.0,500.0,1,0,1,0,0,1,4,2,27,3,1,0,0,0,0,1,1,1.0,1,6,4,1
12,2,1,125.0,2,2,1,0,1,0,1,1,0,29.0,0.0,71.0,57.0,0.0,1,0,1,0,0,0,4,3,23,2,0,0,0,1,1,1,2,0.0,2,13,6,2

In [101]:
## save to CSV
df_sel.to_csv('../data/2017_diabetes_healthindicators.csv', index = False)